/** v0.5.135: exact isolated request routed to the existing App 50 acquisition worker. */
const QBO_ISOLATED_FRESH_V05135=Object.freeze({NAME:'ISOLATED_V3_FRESH_CAPTURE_2609_V05135',RUN:'V3_FRESH_PROOF_PREFILING_2609_1005',META:'00_Fresh_Capture_Proof',PURPOSE:'ISOLATED_FRESH_QBO_CAPTURE_ONLY'});
function qboIsolatedFreshStateV05135_(){
 const I=QBO_ISOLATED_FRESH_V05135,files=DriveApp.getFilesByName(I.NAME),matches=[];while(files.hasNext()){const f=files.next();if(!f.isTrashed())matches.push(f);}if(matches.length!==1||matches[0].getMimeType()!=='application/vnd.google-apps.spreadsheet')throw new Error('V05135_EXACT_FRESH_PROOF_FILE_REQUIRED');
 const book=SpreadsheetApp.openById(matches[0].getId()),asset=DataPlatform05.getConfiguredAssetReference('SALES_TAX_RECONCILIATION_CONTROL','Spreadsheet','PROD'),productionId=asset&&String(asset.ResourceIdentifier||'');if(!productionId||book.getId()===productionId)throw new Error('V05135_PRODUCTION_DESTINATION_FORBIDDEN');const ms=book.getSheetByName(I.META);if(!ms)throw new Error('V05135_FRESH_MARKER_REQUIRED');const meta={};ms.getDataRange().getValues().forEach(r=>{if(meta[r[0]]!==undefined)throw new Error('V05135_DUPLICATE_MARKER');meta[r[0]]=String(r[1]);});
 if(meta.Purpose!==I.PURPOSE||meta.Run_ID!==I.RUN||meta.Proof_Book_ID!==book.getId()||meta.Production_Control_File_ID!==productionId||meta.Setup_Status!=='COMPLETE'||!meta.Request_ID)throw new Error('V05135_FRESH_MARKER_MISMATCH');
 const ledger=book.getSheetByName(QBO_PREFILING_CAPTURE.SHEET_NAME),registry=book.getSheetByName('03_PreFiling_Runs');if(!ledger||!registry||ledger.getLastRow()!==2||registry.getLastRow()!==2)throw new Error('V05135_SINGLE_FRESH_REQUEST_REQUIRED');[ledger,registry].forEach(sh=>{if(sh.getDataRange().getFormulas().some(r=>r.some(Boolean)))throw new Error('V05135_FORMULA_FORBIDDEN');});const state=qboPreFilingReadLedger_(ledger);if(JSON.stringify(state.headers)!==JSON.stringify(QBO_PREFILING_CAPTURE.HEADERS)||state.rows.length!==1)throw new Error('V05135_EXACT_LEDGER_SCHEMA_REQUIRED');const request=state.rows[0],rv=registry.getDataRange().getValues(),run={};rv[0].forEach((h,i)=>run[h]=rv[1][i]);qboIsolatedFreshValidateV05135_(run,request,meta);return {book,ledger,registry,request,run,meta,productionId};
}
function qboIsolatedFreshValidateV05135_(run,q,m){
 const I=QBO_ISOLATED_FRESH_V05135;qboPreFilingValidateRequest_(q);if(run.PreFiling_Run_ID!==I.RUN||run.Evidence_Contract_Version!=='PREFILING_INPUT_V3'||run.Status!=='ACQUIRING'||String(run.USED_FOR_FILING).toUpperCase()!=='FALSE'||String(run.Is_Latest_PreFiling_Run).toUpperCase()!=='FALSE'||run.Level1_Run_ID||run.Evidence_Ready_At)throw new Error('V05135_FRESH_REGISTRY_REQUIRED');if(q.QBO_Capture_Request_ID!==m.Request_ID||q.QBO_Capture_Request_ID!==run.QBO_Capture_Request_ID||q.Capture_Context_Type!=='PREFILING'||q.Capture_Context_ID!==I.RUN||q.PreFiling_Run_ID!==I.RUN||String(q.Period_Key)!=='2609'||qboPreFilingNormalizeDate_(q.Period_Start)!=='2026-09-01'||qboPreFilingNormalizeDate_(q.Period_End)!=='2026-09-30')throw new Error('V05135_EXACT_REQUEST_CONTEXT_REQUIRED');if(!(q.Requested_At instanceof Date)||!(run.Created_At instanceof Date)||q.Requested_At<run.Created_At)throw new Error('V05135_NATIVE_REQUEST_TIMES_REQUIRED');
 if(run.Liability_Snapshot_ID!=='8a9fddf2-3f98-4bb1-92f7-d15c64bbbcd6'||run.Liability_Detail_Snapshot_ID!=='6d3c2865-d772-4298-bb25-1536882e0fe6'||run.Liability_Pairing_Evaluation_ID!=='0a4bb281-5e74-45bf-b7b3-35ab50710801'||run.Liability_Pair_Status!=='PAIR_VALIDATED')throw new Error('V05135_EXACT_PAIR_REQUIRED');
 ['GL_ExtractRunId','GL_SnapshotFileId','Taxable_Sales_Detail_Snapshot_Run_ID','Sales_Tax_Recognition_Snapshot_Run_ID'].forEach(h=>{if(run[h])throw new Error('V05135_UNBOUND_CAPTURE_REQUIRED');});if(['REQUESTED','FAILED','COMPLETE'].indexOf(q.Request_Status)<0)throw new Error('V05135_REQUEST_NOT_PROCESSABLE');if(q.Request_Status==='REQUESTED')QBO_PREFILING_CAPTURE.HEADERS.slice(9,20).forEach(h=>{if(q[h])throw new Error('V05135_NEW_REQUEST_NOT_EMPTY');});
 if(q.Request_Status==='COMPLETE'){
  ['GL_ExtractRunId','GL_SnapshotFileId','Taxable_Sales_Detail_Workbook_File_ID','Taxable_Sales_Detail_Snapshot_Run_ID','Sales_Tax_Recognition_Workbook_File_ID','Sales_Tax_Recognition_Snapshot_Run_ID','Sales_Tax_Recognition_Source_GL_ExtractRunId'].forEach(h=>{if(!q[h])throw new Error('V05135_COMPLETED_EVIDENCE_MISSING: '+h);});
  if(!(q.Processing_Started_At instanceof Date)||!(q.Completed_At instanceof Date)||q.Processing_Started_At<q.Requested_At||q.Completed_At<q.Processing_Started_At||q.Sales_Tax_Recognition_Source_GL_ExtractRunId!==q.GL_ExtractRunId)throw new Error('V05135_CAPTURE_PROVENANCE_FAILED');
  ['GL_ExtractRunId','Taxable_Sales_Detail_Snapshot_Run_ID','Sales_Tax_Recognition_Snapshot_Run_ID'].forEach(h=>{if(!m['Historical_'+h]||String(q[h])===m['Historical_'+h])throw new Error('V05135_HISTORICAL_REUSE_FORBIDDEN');});
 }return true;
}
function qboIsolatedFreshPhysicalV05135_(book){return book.getSheets().map(sh=>{const r=sh.getDataRange();return {name:sh.getName(),values:r.getValues(),formulas:r.getFormulas(),formats:r.getNumberFormats()};});}
function previewSalesTaxIsolatedFreshCaptureV05135(){const s=qboIsolatedFreshStateV05135_(),out={Version:'0.5.135',Status:'PASS',Mode:'READ_ONLY_APP50_FRESH_CAPTURE_PREFLIGHT',Proof_Workbook_ID:s.book.getId(),Request_ID:s.request.QBO_Capture_Request_ID,Request_Status:s.request.Request_Status,Period_Key:'2609',Writes_Performed:0,QBO_Acquisition_Performed:false,Production_Run_Registered:false};safeLog_(JSON.stringify(out));return out;}
function processSalesTaxIsolatedFreshCaptureV05135(){
 const s=qboIsolatedFreshStateV05135_(),production=SpreadsheetApp.openById(s.productionId),baseline=qboIsolatedFreshPhysicalV05135_(production),registryBefore=qboIsolatedFreshPhysicalV05135_(s.book).filter(x=>x.name!==QBO_PREFILING_CAPTURE.SHEET_NAME),key='ISOLATED_FRESH_CAPTURE_LEASE_V05135',props=PropertiesService.getScriptProperties(),token=Utilities.getUuid(),lock=LockService.getScriptLock();if(!lock.tryLock(10000))throw new Error('V05135_LEASE_LOCK_BUSY');try{const prior=props.getProperty(key);if(prior&&Date.now()-Number(JSON.parse(prior).at)<15*60*1000)throw new Error('V05135_CAPTURE_ALREADY_RUNNING');props.setProperty(key,JSON.stringify({token,at:Date.now()}));}finally{lock.releaseLock();}
 try{
  // The existing acquisition processor writes only this single-request proof ledger.
  const result=processSalesTaxPreFilingCaptureRequest(s.book.getId(),s.request.QBO_Capture_Request_ID),after=qboIsolatedFreshStateV05135_();if(after.request.Request_Status!=='COMPLETE')throw new Error('V05135_CAPTURE_NOT_COMPLETE');
  if(JSON.stringify(baseline)!==JSON.stringify(qboIsolatedFreshPhysicalV05135_(production))||JSON.stringify(registryBefore)!==JSON.stringify(qboIsolatedFreshPhysicalV05135_(s.book).filter(x=>x.name!==QBO_PREFILING_CAPTURE.SHEET_NAME)))throw new Error('V05135_CONTROL_OR_PROOF_REGISTRY_CHANGED');
  const out={Version:'0.5.135',Status:'PASS',Mode:'APP50_ISOLATED_FRESH_CAPTURE_COMPLETED',Proof_Workbook_ID:s.book.getId(),Request_ID:result.QBO_Capture_Request_ID,Request_Status:result.Request_Status,GL_ExtractRunId:result.GL_ExtractRunId,GL_SnapshotFileId:result.GL_SnapshotFileId,Taxable_Sales_Detail_Snapshot_Run_ID:result.Taxable_Sales_Detail_Snapshot_Run_ID,Sales_Tax_Recognition_Snapshot_Run_ID:result.Sales_Tax_Recognition_Snapshot_Run_ID,Fresh_Acquisition_Completed:true,Acquisition_Performed_This_Run:s.request.Request_Status!=='COMPLETE',Isolated_Registry_Preserved:true,Production_Control_Preserved:true,Capture_Bound:false,Full_V3_Run_Proven:false};safeLog_(JSON.stringify(out));return out;
 }finally{const l=LockService.getScriptLock();if(l.tryLock(10000)){try{const current=props.getProperty(key);if(current&&JSON.parse(current).token===token)props.deleteProperty(key);}finally{l.releaseLock();}}}
}
function testSalesTaxIsolatedFreshCaptureV05135Contract(){
 const c=[];function ck(n,v){c.push({name:n,passed:!!v});}ck('fresh proof name explicit',QBO_ISOLATED_FRESH_V05135.NAME==='ISOLATED_V3_FRESH_CAPTURE_2609_V05135');ck('production destination prohibited',String(qboIsolatedFreshStateV05135_).indexOf('PRODUCTION_DESTINATION_FORBIDDEN')>=0);ck('single physical request required',String(qboIsolatedFreshStateV05135_).indexOf('getLastRow()!==2')>=0);ck('completed setup marker required',String(qboIsolatedFreshStateV05135_).indexOf("Setup_Status!=='COMPLETE'")>=0);ck('initial evidence must be empty',String(qboIsolatedFreshValidateV05135_).indexOf('NEW_REQUEST_NOT_EMPTY')>=0);ck('old evidence reuse rejected',String(qboIsolatedFreshValidateV05135_).indexOf('HISTORICAL_REUSE_FORBIDDEN')>=0);ck('exact existing worker delegated',String(processSalesTaxIsolatedFreshCaptureV05135).indexOf('processSalesTaxPreFilingCaptureRequest(s.book.getId()')>=0);ck('no latest request operator used',String(processSalesTaxIsolatedFreshCaptureV05135).indexOf('processLatestRequested')<0);ck('short lease claim lock released before export',String(processSalesTaxIsolatedFreshCaptureV05135).indexOf('lock.releaseLock()')<String(processSalesTaxIsolatedFreshCaptureV05135).indexOf('processSalesTaxPreFilingCaptureRequest'));ck('capture does not bind run',!/bindCompleted|setValue|replaceRecords/.test(String(processSalesTaxIsolatedFreshCaptureV05135)));ck('production control preservation checked',String(processSalesTaxIsolatedFreshCaptureV05135).indexOf('CONTROL_OR_PROOF_REGISTRY_CHANGED')>=0);ck('no production run claim',String(processSalesTaxIsolatedFreshCaptureV05135).indexOf('Full_V3_Run_Proven:false')>=0);ck('zero argument operators',previewSalesTaxIsolatedFreshCaptureV05135.length===0&&processSalesTaxIsolatedFreshCaptureV05135.length===0);const passed=c.filter(x=>x.passed).length,out={Version:'0.5.135',Status:passed===c.length?'PASS':'FAIL',Test_Count:c.length,Passed:passed,Checks:c};safeLog_(JSON.stringify(out));if(out.Status!=='PASS')throw new Error('V05135_WORKER_CONTRACT_FAILED');return out;
}
