/** v0.5.136: distinct GL run-snapshot folder; exact single-file placement correction. */
const QBO_GL_ROUTE_V05136=Object.freeze({PROPERTY:'QBO_GL_RUN_SNAPSHOT_FOLDER_ID',FILE:'1pcbY513UJCbF_-OJe-tei-FVg9HwleBB6KfWreZ9iSs',RUN:'15f7d939-3737-465f-93e7-9b1ef0930c80',REQUEST:'3dd8aee5-7b14-4bf2-8255-9514958a5e27'});
function qboGlFolderParentsV05136_(item){const it=item.getParents(),out=[];while(it.hasNext())out.push(it.next().getId());return out.sort();}
function qboGlRunSnapshotFoldersV05136_(){
 const props=PropertiesService.getScriptProperties(),backupId=String(props.getProperty(SCRIPT_PROPERTY_KEYS.SNAPSHOT_FOLDER_ID)||'').trim();if(!backupId)throw new Error('V05136_MASTER_BACKUP_ROUTE_REQUIRED');const backup=DriveApp.getFolderById(backupId);if(backup.getName()!=='Master Backups')throw new Error('V05136_EXPECTED_MASTER_BACKUPS_FOLDER');const parents=qboGlFolderParentsV05136_(backup);if(parents.length!==1)throw new Error('V05136_SINGLE_QUICKBOOKS_PARENT_REQUIRED');const root=DriveApp.getFolderById(parents[0]);if(root.getName()!=='QuickBooks')throw new Error('V05136_QUICKBOOKS_ROOT_REQUIRED');
 const configured=String(props.getProperty(QBO_GL_ROUTE_V05136.PROPERTY)||'').trim();let runFolder;if(configured)runFolder=DriveApp.getFolderById(configured);else{const it=root.getFoldersByName('Run Snapshots'),matches=[];while(it.hasNext())matches.push(it.next());if(matches.length!==1)throw new Error('V05136_UNIQUE_EXISTING_RUN_SNAPSHOTS_REQUIRED');runFolder=matches[0];}
 if(runFolder.getId()===backupId||runFolder.getName()!=='Run Snapshots'||JSON.stringify(qboGlFolderParentsV05136_(runFolder))!==JSON.stringify(parents))throw new Error('V05136_SEPARATE_SIBLING_RUN_FOLDER_REQUIRED');return {backup,runFolder,configured};
}
function qboCorrectFreshGlSnapshotFolderV05136_(write){
 const I=QBO_GL_ROUTE_V05136,s=qboIsolatedFreshStateV05135_();if(s.request.Request_Status!=='COMPLETE'||s.request.QBO_Capture_Request_ID!==I.REQUEST||s.request.GL_ExtractRunId!==I.RUN||s.request.GL_SnapshotFileId!==I.FILE)throw new Error('V05136_EXACT_COMPLETED_CAPTURE_REQUIRED');const route=qboGlRunSnapshotFoldersV05136_(),file=DriveApp.getFileById(I.FILE);if(file.isTrashed()||file.getMimeType()!=='application/vnd.google-apps.spreadsheet'||file.getName().indexOf('QBO_GL_RUN_SNAPSHOT_V2_2026-09-01_to_2026-09-30_15f7d9393737_')!==0)throw new Error('V05136_EXACT_RUN_FILE_REQUIRED');const parents=qboGlFolderParentsV05136_(file),from=route.backup.getId(),to=route.runFolder.getId();if(parents.length!==1||[from,to].indexOf(parents[0])<0)throw new Error('V05136_UNEXPECTED_CURRENT_FILE_PARENT');
 const book=SpreadsheetApp.openById(I.FILE),metadata=book.getSheetByName(QBO_GENERAL_LEDGER_SNAPSHOT_METADATA_SHEET);if(!metadata)throw new Error('V05136_RUN_METADATA_REQUIRED');const meta={};metadata.getDataRange().getValues().slice(1).forEach(r=>meta[String(r[0])]=r[1]);if(meta.ArtifactContract!=='GL_RUN_SNAPSHOT_V2'||meta.ExtractRunId!==I.RUN||Number(meta.RowCount)!==2215||!(meta.ExtractedAt instanceof Date))throw new Error('V05136_RUN_METADATA_MISMATCH');validateQboGeneralLedgerRunSnapshotV2_(I.FILE,I.RUN,'2026-09-01','2026-09-30',2215,meta.ExtractedAt);
 const physical=qboIsolatedFreshPhysicalV05135_(book),ledger=qboIsolatedFreshPhysicalV05135_(s.book),props=PropertiesService.getScriptProperties(),backupProperty=props.getProperty(SCRIPT_PROPERTY_KEYS.SNAPSHOT_FOLDER_ID);let moved=false,configured=false;
 if(write){if(parents[0]!==to){file.moveTo(route.runFolder);moved=true;}if(JSON.stringify(qboGlFolderParentsV05136_(file))!==JSON.stringify([to]))throw new Error('V05136_FILE_MOVE_READBACK_FAILED');if(route.configured!==to){props.setProperty(I.PROPERTY,to);configured=true;}if(props.getProperty(I.PROPERTY)!==to||props.getProperty(SCRIPT_PROPERTY_KEYS.SNAPSHOT_FOLDER_ID)!==backupProperty)throw new Error('V05136_ROUTING_PROPERTY_READBACK_FAILED');}
 if(JSON.stringify(physical)!==JSON.stringify(qboIsolatedFreshPhysicalV05135_(book))||JSON.stringify(ledger)!==JSON.stringify(qboIsolatedFreshPhysicalV05135_(s.book)))throw new Error('V05136_CONTENT_OR_CAPTURE_CHANGED');const out={Version:'0.5.136',Status:write?'PASS':'PREVIEW',Mode:write?'EXACT_GL_RUN_FOLDER_CORRECTION':'READ_ONLY_GL_RUN_FOLDER_PREVIEW',Snapshot_File_ID:I.FILE,GL_ExtractRunId:I.RUN,Current_Parent_ID:qboGlFolderParentsV05136_(file)[0],Master_Backups_Folder_ID:from,Run_Snapshots_Folder_ID:to,File_Move_Planned:parents[0]!==to,File_Moved:moved,Dedicated_Route_Configured:configured,Snapshot_Rows_Verified:2215,File_Identity_Preserved:true,Snapshot_Contents_Preserved:true,Capture_Ledger_Preserved:true,Master_Backup_Route_Unchanged:true,QBO_Acquisition_Performed:false};safeLog_(JSON.stringify(out));return out;
}
function previewFreshGlRunSnapshotFolderV05136(){return qboCorrectFreshGlSnapshotFolderV05136_(false);}
function correctFreshGlRunSnapshotFolderV05136(){return qboCorrectFreshGlSnapshotFolderV05136_(true);}
function testGlRunSnapshotRoutingV05136Contract(){
 const c=[];function ck(n,v){c.push({name:n,passed:!!v});}ck('GL creator uses separate resolver',String(createQboGeneralLedgerRunSnapshotV2_).indexOf('qboGlRunSnapshotFoldersV05136_')>=0);ck('GL creator no longer uses backup property directly',String(createQboGeneralLedgerRunSnapshotV2_).indexOf('SCRIPT_PROPERTY_KEYS.SNAPSHOT_FOLDER_ID')<0);ck('existing Run Snapshots required',String(qboGlRunSnapshotFoldersV05136_).indexOf('UNIQUE_EXISTING_RUN_SNAPSHOTS_REQUIRED')>=0);ck('folder creation prohibited',String(qboGlRunSnapshotFoldersV05136_).indexOf('createFolder')<0);ck('dedicated property distinct',QBO_GL_ROUTE_V05136.PROPERTY!==SCRIPT_PROPERTY_KEYS.SNAPSHOT_FOLDER_ID);ck('exact completed request checked',String(qboCorrectFreshGlSnapshotFolderV05136_).indexOf('EXACT_COMPLETED_CAPTURE_REQUIRED')>=0);ck('exact physical run validator called',String(qboCorrectFreshGlSnapshotFolderV05136_).indexOf('validateQboGeneralLedgerRunSnapshotV2_')>=0);ck('master route checked unchanged',String(qboCorrectFreshGlSnapshotFolderV05136_).indexOf('backupProperty')>=0);ck('file identity never recreated',!/makeCopy|SpreadsheetApp.create|exportQbo/.test(String(qboCorrectFreshGlSnapshotFolderV05136_)));ck('capture and contents preserved',String(qboCorrectFreshGlSnapshotFolderV05136_).indexOf('CONTENT_OR_CAPTURE_CHANGED')>=0);ck('zero argument operators',previewFreshGlRunSnapshotFolderV05136.length===0&&correctFreshGlRunSnapshotFolderV05136.length===0);const passed=c.filter(x=>x.passed).length,out={Version:'0.5.136',Status:passed===c.length?'PASS':'FAIL',Test_Count:c.length,Passed:passed,Checks:c};safeLog_(JSON.stringify(out));if(out.Status!=='PASS')throw new Error('V05136_ROUTING_CONTRACT_FAILED');return out;
}
